### ISSUE TITLE
Correctly determine namespaces with metadata

### ISSUE THREAD

**Issue by technomancy** [technomancy/swank-clojure#1]
Some contrib libraries especially have metadata definitions on namespaces that throw off swank-clojure's namespace detection.

**Comment by luskwater** [comment]
I worked around this by using an 
    (alter-meta!
        _ns_ assoc :doc "Namespace doc")
but that doesn't get picked up by the documentation generator.

**Comment by technomancy** [comment]
Just a note: if you use docstring syntax for namespaces rather than general metadata syntax it works fine. If you have more metadata than just :doc, then patches welcome. =)

**Comment by technomancy** [comment]
This was fixed recently by a patch from Hugo.
