### ISSUE TITLE
Cygwin problems

### ISSUE THREAD

**Issue by MadWombat** [technomancy/swank-clojure#11]
When running under cygwin emacs there is a number of problemsrelated to the fact, that Java is not aware of cygwin paths. Some of these can be solved by replacing swank-clojure-binary with a custom clojure script, but than it fails when attempting to connect to the spawned process, since java cannot find a socket file.

Clojure 1.2.0-master-SNAPSHOT
user=> (require 'swank.swank)
nil
user=> 
user=> (swank.swank/ignore-protocol-version nil)
nil
user=> 
user=> (do (.. java.net.InetAddress getLocalHost getHostAddress) nil)(swank.swank/start-server "/cygdrive/c/DOCUME~1/MADWOM~1/LOCALS~1/Temp/slime.5652" :encoding "iso-latin-1-unix")
nil
java.io.FileNotFoundException: \cygdrive\c\DOCUME~1\MADWOM~1\LOCALS~1\Temp\slime.5652 (The system cannot find the path specified) (NO_SOURCE_FILE:0)
user=> 
user=>

**Comment by MadWombat** [comment]
Here is a preliminary patch, this works for me, not sure if I am breaking anything

<pre>
diff --git a/swank-clojure.el b/swank-clojure.el
index 8d2b3d6..401c2d2 100644
--- a/swank-clojure.el
+++ b/swank-clojure.el
@@ -62,12 +62,18 @@
   :type 'string
   :group 'swank-clojure)
 
+(defun swank-clojure-cygwin () (file-exists-p "/cygdrive/c"))
+
 (defun swank-clojure-default-classpath ()
   (append
    (when (file-directory-p "~/.clojure")
-     (directory-files "~/.clojure" t ".jar$"))
+     (if (swank-clojure-cygwin)
+        (mapcar (lambda (f) (concat "c:/cygwin" (expand-file-name f))) (directory-files "~/.swank-clojure" t ".jar$"))
+       (directory-files "~/.clojure" t ".jar$")))
    (when (file-directory-p swank-clojure-jar-home)
-     (directory-files swank-clojure-jar-home t ".jar$"))))
+     (if (swank-clojure-cygwin)
+        (mapcar (lambda (f) (concat "c:/cygwin" (expand-file-name f))) (directory-files swank-clojure-jar-home t ".jar$"))
+       (directory-files swank-clojure-jar-home t ".jar$")))))
 
 (defcustom swank-clojure-classpath
   (swank-clojure-default-classpath)
@@ -155,7 +161,7 @@ this, keep that in mind."
    ;; where the REPL doesn't pop up until the user presses Enter.
    "(do (.. java.net.InetAddress getLocalHost getHostAddress) nil)"
    (format "(swank.swank/start-server %S :encoding %S)\n\n"
-           (expand-file-name file)
+           (if (swank-clojure-cygwin) (replace-regexp-in-string "\/cygdrive\/c" "c:" file) (expand-file-name file))
            (format "%s" (slime-coding-system-cl-name encoding)))))
 
 (defun swank-clojure-find-package ()
@@ -177,7 +183,9 @@ this, keep that in mind."
 (defun swank-clojure-concat-paths (paths)
   "Concatenate given list of `paths' using `path-separator'. (`expand-file-name'
 will be used over paths too.)"
-  (mapconcat 'identity (mapcar 'expand-file-name paths) path-separator))
+  (if (swank-clojure-cygwin)
+      (mapconcat 'identity paths ";")
+      (mapconcat 'identity (mapcar 'expand-file-name paths) path-separator)))
 
 (defun swank-clojure-parse-jar-name (url)
   (car (last (split-string url "/"))))
</pre>

**Comment by MadWombat** [comment]
This unfortunately does nothing to the server, so things fail when trying to load scripts. I will keep hacking.

**Comment by technomancy** [comment]
Cool; could you submit patches over email or pull requests when you've got it figured out? Thanks.

**Comment by MadWombat** [comment]
OK, even with this patch a lot of things work. I am rather new to emacs/slime, but out of the stuff I tried, only slime-load-file and similar functions sending entire file do not work. I haven't tried the debugger though.

**Comment by technomancy** [comment]
I think I applied this? If not please resubmit.

**Comment by MadWombat** [comment]
I am pretty sure this is not in the main repository. Check if there is cygwin in any of the function names. I will clean it up a bit and resubmit.
