### ISSUE TITLE
It's always 2009-10-15

### ISSUE THREAD

**Issue by vemv** [technomancy/swank-clojure#119]
I switched from clojure-jack-in to the wonderful slime-connect option. The instant connection time just feels so good!

If you forgive the anal-ness, now the initial SLIME prompt always displays "2009-10-15" rather than the usual ms-stamp. Can you do something about it?

Keep up the awesome job.

Victor

**Comment by technomancy** [comment]
> If you forgive the anal-ness, now the initial SLIME prompt always
> displays "2009-10-15" rather than the usual ms-stamp.

Can you explain what you mean by this? Are you getting a prompt warning
you of a version mismatch, or is it something else?

**Comment by vemv** [comment]
This is it:

![](http://i.imgur.com/WeHYP.png)

**Comment by technomancy** [comment]
OK, that's coming from slime rather than swank-clojure. You can upgrade to 20100404 from Marmalade, but anything newer is not guaranteed to be supported since they've introduced incompatibilities upstream.

**Comment by vemv** [comment]
The funny thing is that I didn't touch slime, just began to use slime-connect instead of clojure-jack-in.

for some reason I thought 20100404 was a timestamp reflecting the connection time haha.
