### ISSUE TITLE
debug-repl not really working?

### ISSUE THREAD

**Issue by dedward** [technomancy/swank-clojure#14]
The referenced debug-repl that docs indicate is in swank-clojure 1.2.1 doesn't seem to work for me.  Eg:
- start new empty project with lein
- add :dev-dependencies [[swank-clojure "1.2.1"]] to the project definition
- run lein deps
- run lein swank
- connect from emacs with slime-connect
- try the example in http://hugoduncan.org/post/2010/swank_clojure_gets_a_break_with_the_local_environment.xhtml in the REPL
  - No matter which item I pick in the stack trace, it says "no locals".

Am I overlooking something?
EDIT: fixed to read 1.2.1

**Comment by hugoduncan** [comment]
Which version of clojure? Local require clojure 1.2-SNAPSHOT.

**Comment by dedward** [comment]
That's probably it.. thanks... lein is installing clojure 1.1 jars in projects.....

is the 1.2 requirement documented somewhere that I missed? (just curious.. still learning to navigate the clojure world)

**Comment by dedward** [comment]
That was it..cheers.
