### ISSUE TITLE
extend-protocol issue

### ISSUE THREAD

**Issue by alxchk** [technomancy/swank-clojure#15]
extend-protocol rewrites (not appends) :impl. I.e. I do extend-protocol calls for protocol P with methods A B C for defining methods A B, then call extend-protocol got defining method C. Result: only C method in :impl

**Comment by technomancy** [comment]
What?

**Comment by alxchk** [comment]
What what? :]

**Comment by technomancy** [comment]
I mean I understand that this is a problem, but how is it related to Swank Clojure?

**Comment by alxchk** [comment]
Ow.. I'm sorry. I thought that I'm writing to the clojure issue list ^___^

**Comment by technomancy** [comment]
No worries. Cheers.
