### ISSUE TITLE
(slime-inferior-process) returns nil if using `M-x slime-connect`

### ISSUE THREAD

**Issue by edgargoncalves** [technomancy/swank-clojure#18]
The problem is that (at least) slime-redirect-inferior-output is throwing an error if there's no inferior process, and that happens only if I start slime via `slime-connect` (i.e., a `M-x swank-clojure-project` sets up the inferior-process properly). I know these functions aren't in swank-clojure (slime.el and slime-repl.el), but I suspect this behavior should be connected to it - feel free to redirect me to other discussion places! :)

one workaround could be to detect clojure's particular case, with an advice, maybe, and silent that error (since it doesn't seem to affect me on other lisps, iirc). but we'd still loose everything that depends on a slime-inferior-process... ideas?

**Comment by technomancy** [comment]
Sorry, I don't think anything can be done in swank-clojure; this is definitely a slime bug. slime-redirect-inferior-output should definitely just check for a nil process.

**Comment by edgargoncalves** [comment]
So just to make it clear, you too get a message saying "No inferior Lisp process" each and every time you use  `M-x slime-connect`? If not, how do you fire up your swank server? (I get that even with a simple `lein swank`...)

**Comment by technomancy** [comment]
I use lein swank + M-x slime-connect, but I don't use slime-redirect-inferior-output; it appears that functionality is incompatible with M-x slime-connect.

**Comment by edgargoncalves** [comment]
Ok, thanks! As a quick workaround hack, I've replaced the word "error" by "message" in that function (slime-redirect-inferior-process, so at least I get a cleaner experience :)
