### ISSUE TITLE
slime trunk Oct 31 2009

### ISSUE THREAD

**Issue by gilaras** [technomancy/swank-clojure#2]
Currently swank-clojure does not work with slime trunk as of October 31 2009.  Please look into the following commit in slime that broke slime with swank-clojure.

commit: addc5 be70a489cdc8ed555a2fed7273040da196e
repository: git://git.boinkor.net/slime.git
I had to place a space in the above commit to prevent github from trying to be "smart" and assume the commit its own.

Alternatively see the commit here:
http://github.com/nablaone/slime/commit/22dba9f590a55977f41cb9a333012e9cb6619505

Maybe swank-clojure needs a corresponding swank-match.clj

**Comment by technomancy** [comment]
Should work with a 2010-era slime that's now in elpa.
