### ISSUE TITLE
autodoc and C-c C-d C-d wrong on symbols with =

### ISSUE THREAD

**Issue by scottjad** [technomancy/swank-clojure#24]
It will actually show not for not= and > for >= etc.

**Comment by technomancy** [comment]
Works here. What versions are you using?

**Comment by scottjad** [comment]
swank-clojure 1.3.0-SNAPSHOT and slime latest cvs.

**Comment by technomancy** [comment]
Slime from CVS breaks frequently in unpredictable ways; I don't have the time to make swank-clojure support it. I'd take a patch for this issue though. The supported way is to use version 20100404 of slime.
