### ISSUE TITLE
Unable to start 'lein swank' on a project called swank

### ISSUE THREAD

**Issue by dakrone** [technomancy/swank-clojure#26]
I am unable to start a swank server with the latest clojure 1.3 snapshots, here is my project.clj:

```
(defproject swank "1.0.0"
  :description "Random project for connecting to swank"
  :dependencies [[org.clojure/clojure "1.3.0-master-SNAPSHOT"]
                 [org.clojure.contrib/complete "1.3.0-SNAPSHOT" :classifier "bin"]]
  :dev-dependencies [[swank-clojure "1.3.0-SNAPSHOT"]])
```

Here's the stack trace for starting swank: http://gist.github.com/588399

**Comment by scottjad** [comment]
works for me

**Comment by dakrone** [comment]
Hah, I think I found out what's causing it.

I think it's due to me naming the actual lein project 'swank', if I do a new project and call it 'swank2', it works fine.

Perhaps it's due to the source taking over the swank.core namespace?

If this is true, the bug title should be changed to "Unable to start swank on a project named 'swank'", and perhaps just note it somewhere as a known issue.
