### ISSUE TITLE
"Error in process filter: Wrong number of arguments: nil, 0" Error

### ISSUE THREAD

**Issue by thurn** [technomancy/swank-clojure#31]
Whenever I run swank-clojure through lein on any of my computers, I get an error message when an exception occurs that says "Error in process filter: Wrong number of arguments: nil, 0". In order to reproduce, I just need to do:

lein swank
M-x slime-connect
At this point I get a "Versions differ 2010-10-19 (slime) vs. 20100404 (swank)" warning.
Enter y to Continue anyway
Enter any expression that causes an exception such as (+ "foo" "bar")
The error message is generated

I imagine this is probably tied to the version number warning, but I don't really know what to do about that.

**Comment by nflath** [comment]
I also have this issue.

**Comment by scottjad** [comment]
Are you using [swank-clojure "1.3.0-SNAPSHOT"] ?

**Comment by thurn** [comment]
No, 1.2.1.

Here's a debug trace:

<pre>
Debugger entered--Lisp error: (wrong-number-of-arguments nil 0)
  signal(wrong-number-of-arguments (nil 0))
  (if (= (length --cl-rest--) 1) (car --cl-rest--) (signal (quote wrong-number-of-arguments) (list nil ...)))
  (let* ((--cl-rest-- rand-21444) (_ ...)))
  (cond ((eql op-21443 ...) (let* ... ...)) ((eql op-21443 ...) (let* ...)) (t (error "Elisp destructure-case failed: %S" tmp-21445)))
  (let* ((tmp-21445 G21442) (op-21443 ...) (rand-21444 ...)) (cond (... ...) (... ...) (t ...)))
  (lambda (G21442) (let* (... ... ...) (cond ... ... ...)))((:abort))
  slime-dispatch-event((:return (:abort) 9) #<process SLIME Lisp>)
  slime-process-available-input(#<process SLIME Lisp>)
  slime-net-filter(#<process SLIME Lisp> "000014(:return (:abort) 9)")
</pre>

**Comment by technomancy** [comment]
Looks like you're using Slime from CVS; is that right? Swank-clojure is not supported with any version of slime but the stable ones in ELPA, so it's quite common for breakage to occur with their trunk.

**Comment by mrBliss** [comment]
I'm not sure, but I think I had the same problem with Emacs 23.**1**. Switching to Emacs 23.**2** solved it for me.

**Comment by nflath** [comment]
mrBliss: That isn't it, I'm running 23.2.  It may be that I need slime from ELPA: I haven't tested that yet.

**Comment by thurn** [comment]
Ah, it appears that I was in fact using the wrong version of Slime. This is probably a problem because the first Google hit for "clojure slime" leads you to this blog post:

http://riddell.us/ClojureSwankLeiningenWithEmacsOnLinux.html

Which tells you to set it up with a git checkout of Slime.

**Comment by technomancy** [comment]
Foiled again by Google! Yeah, that blog post has confused many an aspiring Clojurist.

**Comment by mikeandmore** [comment]
@technomancy I was using slime on ELPA with version 20100404, and still get this error.  But my warning about version was Versions differ "nil (slime) vs. 20100404 (swank)"

Can anybody tell me where can I have a working copy of slime just to make swank-clojure work?
