### ISSUE TITLE
enlive html-resource throw slime eof error

### ISSUE THREAD

**Issue by grinnbearit** [technomancy/swank-clojure#32]
using enlive and swank-clojure 1.3.0-SNAPSHOT, html-resource throws a slime end of file error but it works fine with 1.2.1

**Comment by ray1729** [comment]
I'm seeing the same problem with Emacs 23.1.1, slime and slime-repl via ELPA as configured by Technomancy's emacs-starter-kit, and swank-clojure 1.3.0-SNAPSHOT.

**Comment by ModernDude** [comment]
I have the same issue as described above. [Here](https://gist.github.com/919476) are some more details.

**Comment by RickMoynihan** [comment]
I get the same error, is there a fix for this yet?

**Comment by tavisrudd** [comment]
This appears to be fixed in 1.4.0-SNAPSHOT.
