### ISSUE TITLE
Wrapped exception gets unwrapped in slime

### ISSUE THREAD

**Issue by bendlas** [technomancy/swank-clojure#33]
When executing (-main) of this snippet from a slime session, I only see the original exception in the trace.
The wrapping exception is lost.
https://gist.github.com/728427

_Only_ observed on the combination of _clojure 1.3.0-alpha1_ and _swank-clojure 1.3.0-SNAPSHOT_ as pulled in by `lein deps`.

**Comment by technomancy** [comment]
Works for me here; feel free to reopen if you're still seeing it.
