### ISSUE TITLE
java.net.SocketException

### ISSUE THREAD

**Issue by lynaghk** [technomancy/swank-clojure#34]
running `lein swank` I get the following error:
   java.net.SocketException: Invalid argument (NO_SOURCE_FILE:1)
which then prints the `user=>` prompt, then exits.

**Comment by technomancy** [comment]
Going to need some more details.

**Comment by lynaghk** [comment]
I'm fairly new to Java stuff, so let me know if there is some command I can use to dump relevant info for you.

There is another problem that might be related--on this machine Maven cannot download all of the artifacts, even though the urls are all accessible. I just ran `lein deps` on the same project on a different machine and copied `~/.m2` over. Was that unacceptable?
