### ISSUE TITLE
clojure 1.1.0-master-SNAPSHOT dependency missing

### ISSUE THREAD

**Issue by trptcolin** [technomancy/swank-clojure#35]
I noticed recently that swank-clojure 1.1.0 (which some projects, including lein-search, have as a dev-dependency) is now missing its clojure 1.1.0-master-SNAPSHOT dependency, which breaks `lein deps` for all clients of that version of swank-clojure.

Any chance of updating that version to use clojure 1.1.0 instead? 

Not sure why those SNAPSHOTs got deleted; Chas thinks it's normal Maven practice, though: http://groups.google.com/group/clojure-dev/browse_thread/thread/149bc60e05cfaa2e
- Colin

**Comment by technomancy** [comment]
Yes, it's definitely a bug to depend upon a snapshot in a release; this is just something that I messed up on when performing the release. On the other hand it's also a bug to go back and change anything about a version that has already been released. 1.1.0 is quite old; I think a better fix would be for other libraries to switch to 1.2.0.
