### ISSUE TITLE
Shell script but no batch file

### ISSUE THREAD

**Issue by r-moeritz** [technomancy/swank-clojure#37]
```
lein install swank-clojure 1.3.0-SNAPSHOT
```

and we get _~/.lein/bin/swank-clojure_, a shell script...on Windows?? Maybe you could include a batch file instead. [Here's one](https://gist.github.com/745777) I created.

**Comment by technomancy** [comment]
Sure, the shell script is installed for Cygwin users. Are you on the latest Leiningen? Supposedly it has support for installing .bat files, but I haven't tested it myself. If I understand correctly they should be installed automatically, but if not I'd take a patch.

**Comment by Jaskirat** [comment]
Actually, leiningen generates a .bat file but the generated batch file seems to be wrong. 

The batch file seem to be something like this:

set VERSION="swank.swank"

java -cp "%CLASSPATH%" %JVM_OPTS% -Dproject.version=%VERSION%^
 clojure.main -e "(use '1.3.0-SNAPSHOT)(apply -main _command-line-args_)" NUL %*

Clearly the version and the swank.swank seem to be interchanged. I presume this an issue with leiningen.I see that the shell script has been generated properly on windows, which makes it all the more weird.

**Comment by Jaskirat** [comment]
Okay so the bug is in the template i guess

https://github.com/technomancy/leiningen/blob/master/resources/script-template.bat

I am guessing this has to do with the order in which %s is replaced in the template. This is different from the shell script

**Comment by technomancy** [comment]
ISTR this being resolved on the Leiningen side.
