### ISSUE TITLE
Slime freezes when reading from console input

### ISSUE THREAD

**Issue by arohner** [technomancy/swank-clojure#39]
Note, this is distinct from #10. I can't reproduce #10 on my box. 

`(.readLine (clojure.java.io/reader *in*))` will cause the REPL to hang. The same command at the console works just fine.

**Comment by tavisrudd** [comment]
I've just implemented this: https://github.com/technomancy/swank-clojure/commit/f4a1eebc4d34f2ff473c4e5350f889ec356f5168
