### ISSUE TITLE
Swank fails to start because clojure.core/print-doc is not a known var

### ISSUE THREAD

**Issue by seh** [technomancy/swank-clojure#41]
When I try to start swank in Emacs, I see the following error printed to the <code>_inferior-lisp_</code> buffer:

<pre>
Clojure 1.3.0-master-SNAPSHOT
user=> CompilerException java.lang.Exception:
       Unable to resolve var: clojure.core/print-doc in this context, compiling:
       (swank/commands/basic.clj:210) 
</pre>

In file <i>basic.clj</i>, I see the following code:

<pre>
(def print-doc (if (-> #'clojure.core/print-doc meta :private)
                 print-doc*
                 clojure.core/print-doc))
</pre>

The var <code>print-doc</code> is not available:

<pre>
user=> clojure.core/print-doc
       CompilerException java.lang.Exception:
       No such var: clojure.core/print-doc, compiling:(NO_SOURCE_PATH:0) 

user=> #'clojure.core/print-doc
       CompilerException java.lang.Exception: Unable to resolve var:
       clojure.core/print-doc in this context, compiling:(NO_SOURCE_PATH:0) 
</pre>

I see this code changed recently in commit 2b348835d2a22d61de19cf3aa28c121ff23fc5a8, so someone must have found it to be working against a freshly-built Clojure library.

Do I have something configured incorrectly?

**Comment by scottjad** [comment]
I'm not really sure but here are two things to consider: 

If you're "start[ing] swank in Emacs", you should try running lein swank.

My Clojure 1.2.0 has clojure.core/print-doc, maybe you're running an old clojure?

**Comment by scottjad** [comment]
opps, clicked "comment and close" and not sure how to reopen

**Comment by seh** [comment]
I'm running with a freshly-built Clojure 1.3.0 snapshot, from the tip of the "master" branch. I don't use Leiningen, and it should not be necessary to start Swank. It never was before.

I scanned the Clojure source, and the definition of <code>print-doc</code> is in <i>src/clj/clojure/repl.clj</i>, and that definition is private by virtue of <code>defn-</code>.

**Comment by technomancy** [comment]
I have pushed a fix that moves the print-doc lookup to runtime; should work in 1.3 now.

**Comment by seh** [comment]
I verified that the fix works with Clojure 1.3. Thank you for following through so quickly.
