### ISSUE TITLE
slime-load-file :reload-all is inconvenient

### ISSUE THREAD

**Issue by arohner** [technomancy/swank-clojure#44]
The recent commit, https://github.com/technomancy/swank-clojure/commit/115ace416df98c3901daefdbe5b2051d6854dbc0 that adds :reload-all to slime is very inconvenient for a project using defrecords. The :reload-all usually reloads a file containing a defrecord, breaking all 'instance? checks.

**Comment by technomancy** [comment]
Yeah, you shouldn't use C-c C-l unless you want stuff reloaded. C-c C-k is what you want most of the time.
