### ISSUE TITLE
Lose clojure.core/doc in 1.3.0 alpha >= 4

### ISSUE THREAD

**Issue by ejackson** [technomancy/swank-clojure#45]
When using clojure 1.3.0alpha n, where n >= 4 I cannot use (doc foo) at the repl in slime. At the main repl (mvn clojure:repl) it is present.  Where n<4 it functions correctly.

The error is:

Unable to resolve symbol: doc in this context
  [Thrown class java.lang.Exception]

**Comment by jneira** [comment]
Hi! i have the same problem in my windows vista with lein 1.5.2 and swank-clojure 1.3.1
It seems clojure-repl namespace is not loaded, if you (use `clojure.repl) you get access to doc,find-doc,source,etc
thanks

**Comment by bsteuber** [comment]
This has nothing to do with swank - clojure's user-namespace just doesn't include it anymore.
With leiningen 1.6.0, you can add a file ~/.lein/user.clj containing
(use 'clojure.repl)
(use 'clojure.java.javadoc)
which will now be available in your user-namespace.

**Comment by jneira** [comment]
ok , i didnt know about this change, thanks for the tip!

**Comment by ejackson** [comment]
me either, thanks.
