### ISSUE TITLE
SLIME doesn't work when fuzzy completion is enabled

### ISSUE THREAD

**Issue by bbatsov** [technomancy/swank-clojure#50]
If you setup fuzzy completion

(setq slime-complete-symbol-function 'slime-fuzzy-complete-symbol

SLIME freezes on slime-complete-symbol. If there is not intention to implement fuzzy-completion maybe it could at least be made an alias to simple-completion internally at this point.

**Comment by scottjad** [comment]
This also works fine with the supported version of slime.

**Comment by seh** [comment]
Did you mean to close this issue?

**Comment by scottjad** [comment]
Yeah, if this doesn't work for you on the supported version of slime then feel free to reopen, but I think bbatsov was using an unsupported version and it works fine for me on supported version.

**Comment by bbatsov** [comment]
I've tested it with the supported version from ELPA. There I get void-function-definition error.  simple completion works ok there. For me this remains an open issue. I guess someone else should test it as well.

**Comment by scottjad** [comment]
I notice there's a slime-fuzzy package on elpa, are you using that?
Scott

**Comment by bbatsov** [comment]
I just installed SLIME + SLIME REPL from ELPA. Normally SLIME is distributed as a single package. If SLIME fuzzy features the fuzzy completion that would explain a few things. I don't think that it should be separated from the rest of SLIME, though.

**Comment by technomancy** [comment]
> I don't think that it should be separated from the rest of SLIME, though.

I don't think it makes sense either, but the slime devs split out a lot of the functionality into slime-contribs. (including slime-repl; wtf?) It would be nice to create a metapackage that would pull everything in though.
