### ISSUE TITLE
Issue with both 'clojure-jack-in' and 'lein swank'

### ISSUE THREAD

**Issue by jamiltron** [technomancy/swank-clojure#53]
Hello, I previously had swank-clojure working, but since having tried the 'clojure-jack-in' method, I found that it emacs (23.3.1) stated it was starting the swank-server, but would just sit there indefinetely.

Having tried this, when I attempted to go back to using 'lein swank', after I tell emacs to 'slime-connect' I get a usual "repl connected" type message, but none of my buffers switch to a repl, nor are there any selectable buffers that contain a repl.

Perhaps something is wrong with my emacs, but I have tried this with a relatively minimal .emacs setup, just in case.

Any help is appreciated, thank you!

**Comment by technomancy** [comment]
Most of the problems people have had so far are from mixing multiple versions of swank-clojure. Can you make sure you've got only 1.3.1 in ~/.lein-plugins and project.clj?

**Comment by jamiltron** [comment]
Oops, had multiple version in there. Removing those extra versions fixed it. Thank you very much!
