### ISSUE TITLE
jack in not connecting

### ISSUE THREAD

**Issue by bryteise** [technomancy/swank-clojure#62]
Same symptoms as #53 but I don't have any extra versions in the plugins directory or the projects file.

This is the output in the _swank_ buffer after running jack in:

``` elisp
;;; Bootstrapping bundled version of SLIME; please wait...


(when (not (featurep 'slime-c3230b2c))
               (if (file-readable-p "/home/wdouglas/.emacs.d/swank/slime-c3230b2c.elc")
                 (load-file "/home/wdouglas/.emacs.d/swank/slime-c3230b2c.elc")
               (byte-compile-file "/home/wdouglas/.emacs.d/swank/slime-c3230b2c.el" t)))
(when (not (featurep 'slime-repl-79b38c83))
               (if (file-readable-p "/home/wdouglas/.emacs.d/swank/slime-repl-79b38c83.elc")
                 (load-file "/home/wdouglas/.emacs.d/swank/slime-repl-79b38c83.elc")
               (byte-compile-file "/home/wdouglas/.emacs.d/swank/slime-repl-79b38c83.el" t)))
(sleep-for 0.1)

(run-hooks 'slime-load-hook) ; on port 62733
```

And if I use slime-connect at this point on the local port I can get a repl.

**Comment by technomancy** [comment]
Is this new in 1.3.3-SNAPSHOT or does it occur in 1.3.2 as well?

**Comment by bryteise** [comment]
Happens in both, you get a bigger log (as expected from what your 1.3.3 changes did) I can grab that if you'd like as well.

**Comment by bryteise** [comment]
Looking at my home directory:

find . -name '*.jar'
./.lein/plugins/swank-clojure-1.3.3-SNAPSHOT.jar
./.lein/self-installs/leiningen-1.6.1-standalone.jar
./src/my-test/lib/clojure-1.2.1.jar

And if I lein pom && mvn dependency:tree I see:

[INFO] my-test:my-test:jar:1.0.0-SNAPSHOT
[INFO] - org.clojure:clojure:jar:1.2.1:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:51.958s
[INFO] Finished at: Mon Sep 05 04:27:20 PDT 2011
[INFO] Final Memory: 6M/32M

And finally classpath from clojure (I clojure-jackin && slime-connect to):

user> (println (seq (.getURLs (java.lang.ClassLoader/getSystemClassLoader))))

(#<URL file:/home/wdouglas/src/my-test/test/> #<URL file:/home/wdouglas/src/my-test/src/> #<URL file:/home/wdouglas/src\
/my-test/classes/> #<URL file:/home/wdouglas/src/my-test/lib/clojure-1.2.1.jar> #<URL file:/home/wdouglas/.lein/plugins\
/swank-clojure-1.3.3-SNAPSHOT.jar>)

So I'm just not sure what I'm missing (or adding) causing the issue.  The project.clj is a just a lein new.

**Comment by technomancy** [comment]
I believe this is fixed in clojure-mode; if not feel free to reopen in the issue tracker for that project.
