### ISSUE TITLE
clojure-jack-in evaluates output from ~/.lein/init.clj

### ISSUE THREAD

**Issue by manutter51** [technomancy/swank-clojure#64]
If you have an init.clj file in ~/.lein, and that file prints out any text, the clojure-jack-in procedure will attempt to evaluate it as elisp at the beginning of the _swank_ buffer.

To reproduce:
- create an iniit.clj file in ~/.lein and have it execute (println "Loaded init.clj")
- open emacs and type M-x clojure-jack-in
- emacs will eventually report "Error: Symbol's value as a var is void: Loaded"
- open the _swank_ buffer and note the text "Loaded init.clj" at the top of the buffer.

**Comment by technomancy** [comment]
I believe this is fixed in a recent version of clojure-mode.
