### ISSUE TITLE
clojure-jack-out

### ISSUE THREAD

**Issue by grammati** [technomancy/swank-clojure#65]
Enhancement request: a way to reverse the effects of clojure-jack-in.

If I need to restart the repl (eg: because I add or change a dependency), it's not obvious how to do it.  At the moment I'm doing something with ps + grep clojure + kill, which is awkward.

There may already be a way to do this, but I don't see it documented.

Thanks.

**Comment by technomancy** [comment]
In the latest clojure-mode you should be able to just re-run M-x clojure-jack-in, though this may only be in the git version and not in marmalade yet.
