### ISSUE TITLE
[request] make encoding in start-repl configurable

### ISSUE THREAD

**Issue by spariev** [technomancy/swank-clojure#7]
It would be nice to be able to use utf-8 and other encodings instead of iso-latin-1-unix. Currently I can't even evaluate forms like  (println "привет").

**Comment by wilig** [comment]
Try adding this to your configuration:

(eval-after-load "slime"
  '(progn
     (setq slime-net-coding-system 'utf-8-unix)
     (slime-setup)))

That should set the encoding to UTF-8.

**Comment by spariev** [comment]
Thank you for advice, but it didn't help my case. The reason is the hardcoded encoding in http://github.com/technomancy/swank-clojure/blob/master/src/swank/swank.clj , if I change it to utf-8-unix, it all works fine.

**Comment by purcell** [comment]
There appears to be a fix for this in marktriggs' recent fork: "added a new swank.encoding property"

**Comment by spariev** [comment]
closing, now encoding could be set with -Dswank.encoding=utf-8 JVM option
