### ISSUE TITLE
clojure-jack-in does not load lib/dev on classpath

### ISSUE THREAD

**Issue by locopati** [technomancy/swank-clojure#70]
I have a project set up with dependencies and dev-dependencies where swank-clojure is installed by lein as a plugin.

`lein deps` populates `lib` and `lib/dev` with jars
`M-x clojure-jack-in` opens a REPL
However, libraries in `lib/dev` cannot be found.
I would expect `lib/dev` to be part of the classpath in the REPL.

Workaround is to move dev-dependencies back to dependencies

If exists is a way to make this work (either a project.clj setting or an elisp command), documentation is needed.

**Comment by technomancy** [comment]
Is this specific to jack-in, or does it happen with other tasks? Is it specific to the directory from which M-x clojure-jack-in is invoked?
