### ISSUE TITLE
Ant not found (itermittent problem)

### ISSUE THREAD

**Issue by locopati** [technomancy/swank-clojure#71]
Running `lein deps` sometimes causes
`Caused by: java.io.FileNotFoundException: /home/andy/dev/player-se/lib/dev/ant-1.8.2.jar (No such file or directory)`

Running the command again will work. This is happening within Emacs after making a change to dependencies and running the command in an in-emacs shell.

**Comment by technomancy** [comment]
I need more details about where you are seeing this problem.
