### ISSUE TITLE
Running lein deps from slime

### ISSUE THREAD

**Issue by paddymul** [technomancy/swank-clojure#83]
Is it possible to add a new dependency to a project via slime, and have leiningen pull down that dependency in the same running jvm, if so, how?

basically, I find that I have to start lein swank , add a dependency, stop lein swank, lein deps, start lein swank

**Comment by technomancy** [comment]
On Sun, Nov 20, 2011 at 11:22 AM, Paddy Mullen
reply@reply.github.com
wrote:

> Is it possible to add a new dependency to a project via slime, and have leiningen pull down that dependency in the same running jvm, if so, how?

This is planned for Leiningen 2.0, but we don't have anything yet.

**Comment by technomancy** [comment]
This is possible using [pomegranate](https://github.com/cemerick/pomegranate).
