### ISSUE TITLE
IllegalArgumentException thrown at REPL

### ISSUE THREAD

**Issue by RickMoynihan** [technomancy/swank-clojure#9]
I get this exception thrown at the Swank REPL... But not when running the same code at the commandline:

No matching method found: println for class swank.util.io.proxy$java.io.StringWriter$0
  [Thrown class java.lang.IllegalArgumentException]

Restarts:
 0: [ABORT] Return to SLIME's top level.

Backtrace:
  0: clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:50)
  1: clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
  2: clojure.contrib.sql.internal$print_update_counts__7348.invoke(internal.clj:132)
  3: clojure.contrib.sql.internal$transaction_STAR___7362.invoke(internal.clj:162)
  4: clojure.contrib.sql$do_commands__7390.doInvoke(sql.clj:89)
  5: clojure.lang.RestFn.invoke(RestFn.java:413)
  6: clojure.contrib.sql$create_table__7430.doInvoke(sql.clj:119)
  7: clojure.lang.RestFn.invoke(RestFn.java:428)
  8: myproject.record$create_schema_version_table__3688.invoke(NO_SOURCE_FILE:1)
  9: myproject.record$migrate__3465$fn__3469.invoke(NO_SOURCE_FILE:1)
 10: clojure.contrib.sql.internal$with_connection_STAR___7339.invoke(internal.clj:105)
 11: myproject.record$migrate__3465.invoke(NO_SOURCE_FILE:1)
 12: myproject.record$migrate__3465.invoke(NO_SOURCE_FILE:1)
 13: myproject.record$eval__3735.invoke(NO_SOURCE_FILE:1)
 14: clojure.lang.Compiler.eval(Compiler.java:4642)
 15: clojure.core$eval__5236.invoke(core.clj:2017)
 16: swank.commands.basic$eval_region__912.invoke(basic.clj:40)
 17: swank.commands.basic$eval_region__912.invoke(basic.clj:31)
 18: swank.commands.basic$eval__932$listener_eval__934.invoke(basic.clj:54)
 19: clojure.lang.Var.invoke(Var.java:359)
 20: myproject.record$eval__3732.invoke(NO_SOURCE_FILE)
 21: clojure.lang.Compiler.eval(Compiler.java:4642)
 22: clojure.core$eval__5236.invoke(core.clj:2017)
 23: swank.core$eval_in_emacs_package__460.invoke(core.clj:59)
 24: swank.core$eval_for_emacs__538.invoke(core.clj:128)
 25: clojure.lang.Var.invoke(Var.java:367)
 26: clojure.lang.AFn.applyToHelper(AFn.java:179)
 27: clojure.lang.Var.applyTo(Var.java:476)
 28: clojure.core$apply__4370.invoke(core.clj:436)
 29: swank.core$eval_from_control__463.invoke(core.clj:66)
 30: swank.core$eval_loop__466.invoke(core.clj:71)
 31: swank.core$spawn_repl_thread__600$fn__632$fn__634.invoke(core.clj:183)
 32: clojure.lang.AFn.applyToHelper(AFn.java:171)
 33: clojure.lang.AFn.applyTo(AFn.java:164)
 34: clojure.core$apply__4370.invoke(core.clj:436)
 35: swank.core$spawn_repl_thread__600$fn__632.doInvoke(core.clj:180)
 36: clojure.lang.RestFn.invoke(RestFn.java:402)
 37: clojure.lang.AFn.run(AFn.java:37)
 38: java.lang.Thread.run(Thread.java:637)

**Comment by RickMoynihan** [comment]
I think this is might be a dupe of the issues presented here:

http://www.mail-archive.com/clojure@googlegroups.com/msg24446.html

I'm not clear on what the outcomes of this thread are.

**Comment by technomancy** [comment]
I believe this is fixed in the latest swank.
